version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432" #PASSAR VOLUME PARA PERSITENCIA DE DADOS
    volumes:
      - .:/code
  
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 eventcalendar.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
